version: "3"

services:
  mysql:
    build: ./mysql
    container_name: mysql
    platform: linux/x86_64
    env_file:
      - ./mysql/db.env
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
    ports:
      - 3306:3306

  java:
    image: openjdk:17
    container_name: java
    env_file:
      - ./mysql/db.env
    tty: true
    working_dir: /app
    volumes:
      - ./app:/app
    command: sh ./entrypoint.sh
    ports:
      - 8080:8080
      - 5050:5050
    depends_on:
      - mysql
